name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: "3.12"

      - name: Install dependencies
        run: uv sync --group ci --group test

      - name: Run pre-commit checks
        run: uv run pre-commit run --all-files

      - name: Run tests for all supported Python versions
        run: uv run hatch test -a
